bi_backend/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# THE FOLLOWING FUNCTION WILL HELP US TO HANDLE THE UNAVAILABLE LINK OR WEB PAGE
handler404 = "main.views.handle_not_found"


# Configure Admin Title
admin.site.site_header = "BOUTIQUE IBITANGAZA MANAGEMENT SYSTEM"
admin.site.index_title = "MANAGEMENT"
admin.site.site_title = "Control Panel"

main/urls.py
from django.urls import path
from main import views


urlpatterns = [
    path('', views.home, name='home'),
    path('shop/about/', views.about, name='about'),
    path('shop/contact/', views.contact, name='contact'),
    path('shop/', views.shop, name='shop'),
    path('shop/category/<str:name>/', views.shopCategory, name='shop_category'),
    path('shop/search/', views.search_result, name='search_result'),
    path('shop/search/<str:search_data>/', views.search_result, name='search_result'),
    path('shop/product/<int:pk>/product_details/', views.product_details, name='product_details'),
    # cart urls
    path('shop/cart/', views.shop_cart, name='shop_cart'),
    path('shop/cart/add_to_cart/<int:product_id>/', views.addToCart, name='add_to_cart'),
    path('shop/cart/update_cart/', views.updateCart, name='update_cart'),
    path('shop/cart/remove_from_cart/<int:product_id>/', views.removeFromCart, name='remove_from_cart'),

    path('shop/checkout/', views.shop_checkout, name='shop_checkout'),
    path('shop/order_confirmation/', views.order_confirmation, name='order_confirmation'),
    path('shop/client/login/', views.client_login, name='client_login'),
    path('shop/client/register/', views.client_register, name='client_register'),
    path('shop/client/logout/', views.client_logout, name='client_logout'),
    path('shop/client/dashboard/', views.client_dashboard, name='client_account'),
    path('shop/client/profile/', views.client_profile, name='client_profile'),
    path('shop/client/order_list/', views.client_order_list, name='client_order_list'),
    path('shop/client/order_list/<int:pk>/', views.client_order_details, name='client_order_details'),
]

account/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from . manager import UserManager


# Create your models here.
class User(AbstractUser):
    class Gender(models.TextChoices):
        SELECT = "", "Select Gender"
        MALE = "Male", "Male"
        FEMALE = "Female", "Female"

    first_name = models.CharField(verbose_name="First Name", max_length=50, blank=False)
    last_name = models.CharField(verbose_name="Last Name", max_length=50, blank=False)
    email = models.EmailField(verbose_name="Email", max_length=255, unique=True, blank=False)
    gender = models.CharField(verbose_name="Gender", choices=Gender.choices, default=Gender.SELECT, max_length=10)
    is_manager = models.BooleanField(verbose_name="Is Manger", default=False)
    is_client = models.BooleanField(verbose_name="Is Client", default=False)

    username = None

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()

    # update django about user model
    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)



class ClientProfile(models.Model):
    client = models.OneToOneField(settings.AUTH_USER_MODEL, related_name="client_profile", verbose_name="Client", on_delete=models.CASCADE)
    phone_number = PhoneNumberField(verbose_name = "Phone Number", blank=True, unique=True)
    location = models.CharField(verbose_name="Location", max_length=100, blank=True, null=True)
    shipping_location = models.CharField(verbose_name="Shipping Location", max_length=100, blank=True, null=True)
    shipping_street = models.CharField(verbose_name="Shipping Street", max_length=50, blank=True, null=True)
    def __str__(self):
        return "{} {}".format(self.client.first_name, self.client.last_name)

main/views.py
import random
from django.shortcuts import redirect, render
from django.contrib import messages
from django.core.mail import EmailMessage
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model, authenticate, login, logout, update_session_auth_hash

from django.db.models import Q

from main.models import *
from account.models import ClientProfile


# my functions
def search_products_filter(search_data=None):
    if search_data:
        # get data where category name contains search_data or product name contains search_data
        matched_products = ProductDetail.objects.filter(Q(product__category__category_name__icontains=search_data) | Q(product__product_name__icontains=search_data))
    return matched_products



# Create your views here.
def handle_not_found(request, exception):
    if 'search' in request.POST:
        search_data = request.POST.get("search_data")

        if search_data:
            # Call the search_result function and pass the data
            return search_result(request, search_data)
        else:
            return redirect(shop)
    else:
        context = {
            'title': 'Page Not found',
        }
        return render(request, 'main/404.html', context)



def home(request):
    if 'search' in request.POST:
        search_data = request.POST.get("search_data")

        if search_data:
            # Call the search_result function and pass the data
            return search_result(request, search_data)
        else:
            return redirect(shop)
    else:
        categories = ProductCategory.objects.filter()
        context = {
            'title': 'Welcome',
            'categories': categories,
        }
        return render(request, 'main/home.html', context)



def about(request):
    if 'search' in request.POST:
        search_data = request.POST.get("search_data")

        if search_data:
            # Call the search_result function and pass the data
            return search_result(request, search_data)
        else:
            return redirect(shop)
    else:
        context = {
            'title': 'About us',
        }
        return render(request, 'main/about.html', context)



def contact(request):
    if 'search' in request.POST:
        search_data = request.POST.get("search_data")

        if search_data:
            # Call the search_result function and pass the data
            return search_result(request, search_data)
        else:
            return redirect(shop)
    else:
        context = {
            'title': 'Contact us',
        }
        return render(request, 'main/contact.html', context)



def shop(request):
    if 'search' in request.POST:
        search_data = request.POST.get("search_data")

        if search_data:
            # Call the search_result function and pass the data
            return search_result(request, search_data)
        else:
            return redirect(shop)
    else:
        categories = ProductCategory.objects.filter()
        products = ProductDetail.objects.filter()
        context = {
            'title': 'Shop',
            'categories': categories,
            'products': products,
        }
        return render(request, 'main/shop.html', context)



def search_result(request, search_data=None):
    if search_data:
        # Call the search_products_filter function to get the filtered products
        filtered_products = search_products_filter(search_data)

        categoryData = ProductCategory.objects.filter()
        context = {
            'title': 'Shop - Search Result',
            'categories': categoryData,
            'products': filtered_products,
        }
        return render(request, 'main/search_result.html', context)
    else:
        return redirect(shop)



def shopCategory(request, name):
    category_name = name
    # check if category exist
    if ProductCategory.objects.filter(category_name=category_name).exists():
        # if exists
        selectedCategory = ProductCategory.objects.get(category_name=category_name)
        products = ProductDetail.objects.filter(product__category=selectedCategory)

        if 'search' in request.POST:
            search_data = request.POST.get("search_data")

            if search_data:
                # Call the search_result function and pass the data
                return search_result(request, search_data)
            else:
                return redirect(shop)
        else:
            categories = ProductCategory.objects.filter()
            context = {
                'title': 'Shop - category',
                'categories': categories,
                'products': products,
                'selectedCategory': selectedCategory,
            }
            return render(request, 'main/shop.html', context)
    else:
        messages.error(request, ('Product Category not found'))
        return redirect(shop)




def product_details(request, pk):
    product_id = pk
    # check if category exist
    if ProductDetail.objects.filter(id=product_id).exists():
        # if exists
        selected_product = ProductDetail.objects.get(id=product_id)

        if 'search' in request.POST:
            search_data = request.POST.get("search_data")

            if search_data:
                # Call the search_result function and pass the data
                return search_result(request, search_data)
            else:
                return redirect(shop)
        else:
            categories = ProductCategory.objects.filter()
            context = {
                'title': 'Shop - Product details',
                'categories': categories,
                'p_data': selected_product,
            }
            return render(request, 'main/product_details.html', context)
    else:
        messages.error(request, ('Product not found'))
        return redirect(shop)



def shop_cart(request):
    if 'search' in request.POST:
        search_data = request.POST.get("search_data")

        if search_data:
            # Call the search_result function and pass the data
            return search_result(request, search_data)
        else:
            return redirect(shop)
    else:
        # get data from cart
        cart = request.session.get('cart', {})
        cart_items = []
        total_price = 0
        for product_id, item in cart.items():
            p_data = ProductDetail.objects.get(id=int(product_id))
            item['p_data'] = p_data
            item['subtotal'] = p_data.product.price * item['quantity']
            total_price += item['subtotal']
            cart_items.append(item)

        else:
            # return the value to template
            context ={
                'title': 'Shop - Cart',
                'cart_items': cart_items,
                'total_price': total_price,
            }
            return render(request, 'main/shop_cart.html', context)



def addToCart(request, product_id):
    # get quantity is provided
    if request.POST.get('qty'):
        quantity = float(request.POST.get('qty'))
    else:
        quantity = 1

    cart = request.session.get('cart', {})
    cart_item = cart.get(str(product_id), {'quantity': 0})
    cart_item['quantity'] += quantity
    cart[str(product_id)] = cart_item
    request.session['cart'] = cart
    return redirect(shop_cart)


def updateCart(request):
    # update cart values
    if 'update_cart' in request.POST:
        cart = request.session.get('cart', {})
        for product_id, quantity in request.POST.items():
            if product_id.startswith('quantity_'):
                product_id = product_id.split('_')[1]
                cart_item = cart.get(str(product_id), {'quantity': 0})
                cart_item['quantity'] = float(quantity)
                cart[str(product_id)] = cart_item
        request.session['cart'] = cart
    return redirect(shop_cart)



def removeFromCart(request, product_id):
    cart = request.session.get('cart', {})
    if str(product_id) in cart:
        del cart[str(product_id)]
        request.session['cart'] = cart
    return redirect(shop_cart)




@login_required(login_url='shop')
def shop_checkout(request):
    if request.user.is_authenticated and request.user.is_client==True:
        if 'search' in request.POST:
            search_data = request.POST.get("search_data")
            if search_data:
                # Call the search_result function and pass the data
                return search_result(request, search_data)
            else:
                return redirect(shop)
        else:
            return render(request, 'main/checkout.html')
    else:
        messages.warning(request, ('You have to login to view the page!'))
        return redirect(shop)



@login_required(login_url='shop')
def order_confirmation(request):
    if request.user.is_authenticated and request.user.is_client==True:
        if 'place_order' in request.POST:
            shipping_location = request.POST.get("shipping_location")
            shipping_street = request.POST.get("shipping_street")
            pay_method = request.POST.get("pay_method")
            payment_id = request.POST.get("payment_id")

            # Generate a random number for order number
            order_no = random.randint(1, 1000000)

            # get data from cart to get total_amount
            cart = request.session.get('cart', {})
            total_price = 0
            for product_id, item in cart.items():
                p_data = ProductDetail.objects.get(id=int(product_id))
                total_price += p_data.product.price * item['quantity']

            # add new order
            client_order = Order(
                client = get_user_model().objects.get(email=request.user.email),
                order_number =order_no,
                status = 'Pending',
                shipping_address = shipping_location+"/ "+shipping_street,
                total_amount = total_price,

templates/main/includes/cart.html
{% load static %}
<div class="dropdown cart-dropdown">
  <a
    href="#"
    class="dropdown-toggle"
    role="button"
    data-toggle="dropdown"
    aria-haspopup="true"
    aria-expanded="false"
    data-display="static"
  >
    <i class="icon-shopping-cart"></i>
    <span class="cart-count">{{cart_items|length}}</span>
  </a>

  <div class="dropdown-menu dropdown-menu-right">
    {% if cart_items %}
    <div class="dropdown-cart-products">
      {% for item in cart_items %}
      <div class="product">
        <div class="product-cart-details">
          <h4 class="product-title">
            <a href="product.html">
              {{item.p_data.color}} {{item.p_data.product.product_name}}
            </a>
          </h4>

          <span class="cart-product-info">
            Frw {{item.p_data.product.price}} x
            <span class="cart-product-qty">{{item.quantity}}m</span>
          </span>
        </div>
        <!-- End .product-cart-details -->

        <figure class="product-image-container">
          <a
            href="{% url 'product_details' item.p_data.id %}"
            class="product-image"
          >
            {% if item.p_data.picture %}
            <img src="{{item.p_data.picture.url}}" alt="product" />
            {% else %}
            <img src="" alt="product" />
            {% endif %}
          </a>
        </figure>
        <a
          href="{% url 'remove_from_cart' item.p_data.id %}"
          class="btn-remove"
          title="Remove Product"
        >
          <i class="icon-close"></i>
        </a>
      </div>
      <!-- End .product -->
      {% endfor %}
    </div>
    <!-- End .cart-product -->

    <div class="dropdown-cart-total">
      <span>Total</span>

      <span class="cart-total-price">Frw {{total_price}}</span>
    </div>
    <!-- End .dropdown-cart-total -->

    <div class="dropdown-cart-action">
      <a href="{% url 'shop_cart' %}" class="btn btn-primary">View Cart</a>
      {% if user.is_authenticated %}
      <a href="{% url 'shop_checkout' %}" class="btn btn-outline-primary-2">
        <span>Checkout</span> <i class="icon-long-arrow-right"></i>
      </a>
      {% endif %}
    </div>
    <!-- End .dropdown-cart-total -->
    {% else %}
    <div class="dropdown-cart-products py-5">
      <p>Your Cart is Empty</p>
    </div>
    {% endif %}
  </div>
  <!-- End .dropdown-menu -->
</div>

templates/main/includes/client_sidebar.html
<aside class="col-md-4 col-lg-3">
  <ul class="nav nav-dashboard flex-column mb-3 mb-md-0">
    <li class="nav-item">
      <a
        class="nav-link {{dashboard_active}}"
        href="{% url 'client_account' %}"
      >
        Dashboard
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {{profile_active}}" href="{% url 'client_profile' %}">
        My Profile
      </a>
    </li>
    <li class="nav-item">
      <a
        class="nav-link {{orders_active}}"
        href="{% url 'client_order_list' %}"
      >
        Orders
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'client_logout' %}"> Sign Out </a>
    </li>
  </ul>
</aside>

templates/main/includes/footer.html
{% load static %}
<footer class="footer footer-dark">
  <div class="footer-middle">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-lg-6">
          <div class="widget widget-about">
            <h4 class="widget-title">Boutique Ibitangaza</h4>
            <p>
              Praesent dapibus, neque id cursus ucibus, tortor neque egestas
              augue, eu vulputate magna eros eu erat.
            </p>
          </div>
          <!-- End .widget about-widget -->
        </div>
        <!-- End .col-sm-6 col-lg-3 -->

        <div class="col-sm-6 col-lg-3">
          <div class="widget">
            <h4 class="widget-title">Useful Links</h4>
            <!-- End .widget-title -->

            <ul class="widget-list">
              <li><a href="about.html">About Molla</a></li>
              <li><a href="#">How to shop on Molla</a></li>
              <li><a href="#">FAQ</a></li>
              <li><a href="contact.html">Contact us</a></li>
              <li><a href="login.html">Log in</a></li>
            </ul>
            <!-- End .widget-list -->
          </div>
          <!-- End .widget -->
        </div>
        <!-- End .col-sm-6 col-lg-3 -->

        <div class="col-sm-6 col-lg-3">
          <div class="widget">
            <h4 class="widget-title">Customer Service</h4>
            <!-- End .widget-title -->

            <ul class="widget-list">
              <li><a href="#">Payment Methods</a></li>
              <li><a href="#">Money-back guarantee!</a></li>
              <li><a href="#">Returns</a></li>
              <li><a href="#">Shipping</a></li>
              <li><a href="#">Terms and conditions</a></li>
              <li><a href="#">Privacy Policy</a></li>
            </ul>
            <!-- End .widget-list -->
          </div>
          <!-- End .widget -->
        </div>
      </div>
      <!-- End .row -->
    </div>
    <!-- End .container -->
  </div>
  <!-- End .footer-middle -->

  <div class="footer-bottom">
    <div class="container">
      <p class="footer-copyright">
        Copyright © 2023 Boutique Ibitangaza. All Rights Reserved.
        <span class="float-right">Rudasigwa Bian</span>
      </p>
    </div>
    <!-- End .container -->
  </div>
  <!-- End .footer-bottom -->
</footer>

templates/main/includes/login_register.html
{% load static %}
<div
  class="modal fade"
  id="signin-modal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true"><i class="icon-close"></i></span>
        </button>

        <div class="form-box">
          <h4 class="form-title text-center">Client Account</h4>
          <div class="form-tab">
            <ul class="nav nav-pills nav-fill" role="tablist">
              <li class="nav-item">
                <a
                  class="nav-link active"
                  id="signin-tab"
                  data-toggle="tab"
                  href="#signin"
                  role="tab"
                  aria-controls="signin"
                  aria-selected="true"
                >
                  Sign In
                </a>
              </li>
              <li class="nav-item">
                <a
                  class="nav-link"
                  id="register-tab"
                  data-toggle="tab"
                  href="#register"
                  role="tab"
                  aria-controls="register"
                  aria-selected="false"
                >
                  Register
                </a>
              </li>
            </ul>
            <div class="tab-content" id="tab-content-5">
              <div
                class="tab-pane fade show active"
                id="signin"
                role="tabpanel"
                aria-labelledby="signin-tab"
              >
                <form action="{% url 'client_login' %}" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="email">Email address *</label>
                    <input
                      type="text"
                      class="form-control"
                      id="email"
                      name="email"
                      required
                    />
                  </div>
                  <!-- End .form-group -->

                  <div class="form-group">
                    <label for="password">Password *</label>
                    <input
                      type="password"
                      class="form-control"
                      id="password"
                      name="password"
                      required
                    />
                  </div>
                  <!-- End .form-group -->

                  <div class="form-footer">
                    <button
                      type="submit"
                      name="login"
                      class="btn btn-outline-primary-2"
                    >
                      <span>LOG IN</span>
                      <i class="icon-long-arrow-right"></i>
                    </button>
                  </div>
                  <!-- End .form-footer -->
                </form>
              </div>
              <!-- .End .tab-pane -->
              <div
                class="tab-pane fade"
                id="register"
                role="tabpanel"
                aria-labelledby="register-tab"
              >
                <form action="{% url 'client_register' %}" method="POST">
                  {% csrf_token %}
                  <div class="row">
                    <div class="form-group col-6">
                      <label for="id_first_name">First Name</label>
                      <input
                        type="text"
                        class="form-control"
                        id="id_first_name"
                        name="first_name"
                        required
                      />
                    </div>
                    <div class="form-group col-6">
                      <label for="id_last_name">Last Name</label>
                      <input
                        type="text"
                        class="form-control"
                        id="id_last_name"
                        name="last_name"
                        required
                      />
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="id_gender">Gender</label>
                    <select
                      class="form-control"
                      id="id_gender"
                      name="gender"
                      required
                    >
                      <option selected disabled>Select Gender</option>
                      <option value="Male">Male</option>
                      <option value="Female">Female</option>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="id_phone_number">Phone Number</label>
                    <input
                      type="text"
                      class="form-control"
                      id="id_phone_number"
                      name="phone_number"
                    />
                  </div>
                  <div class="form-group">
                    <label for="id_location">Location</label>
                    <input
                      type="text"
                      class="form-control"
                      id="id_location"
                      name="location"
                    />
                  </div>
                  <div class="form-group">
                    <label for="id_email">Email address *</label>
                    <input
                      type="email"
                      class="form-control"
                      id="id_email"
                      name="email"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="id_password1">New Password *</label>
                    <input
                      type="password"
                      class="form-control"
                      id="id_password1"
                      name="password1"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="id_password2">Confirm Password *</label>
                    <input
                      type="password"
                      class="form-control"
                      id="id_password2"
                      name="password2"
                      required
                    />
                  </div>
                  <div class="form-footer">
                    <button
                      type="submit"
                      name="sign_up"
                      class="btn btn-outline-primary-2"
                    >
                      <span>SIGN UP</span>
                      <i class="icon-long-arrow-right"></i>
                    </button>
                  </div>
                </form>
              </div>
              <!-- .End .tab-pane -->
            </div>
            <!-- End .tab-content -->
          </div>
          <!-- End .form-tab -->
        </div>
        <!-- End .form-box -->
      </div>
      <!-- End .modal-body -->
    </div>
    <!-- End .modal-content -->
  </div>
  <!-- End .modal-dialog -->
</div>

templates/main/includes/mobile_menu.html
{% load static %}
<div class="mobile-menu-container">
  <div class="mobile-menu-wrapper">
    <span class="mobile-menu-close"><i class="icon-close"></i></span>

    <form action="" method="POST" class="mobile-search">
      {% csrf_token %}
      <label for="search_data" class="sr-only">Search</label>
      <input
        type="search"
        class="form-control"
        name="search_data"
        id="search_data"
        placeholder="Search in..."
        required
      />
      <button class="btn btn-primary" name="search" type="submit">
        <i class="icon-search"></i>
      </button>
    </form>

    <nav class="mobile-nav">
      <ul class="mobile-menu">
        <li class="active">
          <a href="index.html">Home</a>
        </li>
        <li>
          <a href="category.html">Shop</a>
        </li>
        <li>
          <a href="about.html">About</a>
        </li>
        <li>
          <a href="blog.html">Contact</a>
        </li>
      </ul>
    </nav>
    <!-- End .mobile-nav -->
  </div>
  <!-- End .mobile-menu-wrapper -->
</div>

templates/main/includes/navbar.html
{% load static %}
<header class="header">
  <div class="header-top pt-3">
    <div class="container py-3">
      <div class="header-left">
        <a href="tel:#"> <i class="icon-phone"></i> Call: +250 789 061 369 </a>
      </div>
      <!-- End .header-left -->
      <div class="header-right">
        {% if not user.is_authenticated %}
        <a href="#signin-modal" data-toggle="modal">
          <i class="icon-user"></i>Login
        </a>
        {% else %}
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <i class="icon-user"></i>
          {{user.first_name}} {{user.last_name}}
        </a>
        <ul class="dropdown-menu dropdown-menu-right">
          <li class="nav-item text-lg">
            <a class="btn btn-sm" href="{% url 'client_account' %}">
              <i class="icon-user"></i> Account</a
            >
          </li>
          <li class="nav-item text-lg">
            <a class="btn btn-sm" href="{% url 'client_logout' %}">
              <i class="icon-long-arrow-left"></i> Sign out</a
            >
          </li>
        </ul>
        {% endif %}
      </div>
      <!-- End .header-right -->
    </div>
    <!-- End .container -->
  </div>
  <!-- End .header-top -->

  <div class="header-middle sticky-header">
    <div class="container">
      <div class="header-left">
        <button class="mobile-menu-toggler">
          <span class="sr-only">Toggle mobile menu</span>
          <i class="icon-bars"></i>
        </button>

        <a href="{% url 'home' %}" class="logo">
          <h3 class="pt-1">Boutique Ibitangaza</h3>
        </a>

        <nav class="main-nav">
          <ul class="menu sf-arrows">
            <li class="active">
              <a href="{% url 'home' %}">Home</a>
            </li>
            <li>
              <a href="{% url 'shop' %}">Shop</a>
            </li>
            <li>
              <a href="{% url 'about' %}">About</a>
            </li>
            <li>
              <a href="{% url 'contact' %}">Contact</a>
            </li>
          </ul>
        </nav>
      </div>
      <!-- End .header-left -->

      <div class="header-right">
        <div class="header-search">
          <a href="#" class="search-toggle" role="button" title="Search"
            ><i class="icon-search"></i
          ></a>
          <form action="" method="POST">
            {% csrf_token %}
            <div class="header-search-wrapper">
              <label for="search_data" class="sr-only">Search</label>
              <input
                type="search"
                class="form-control"
                name="search_data"
                id="search_data"
                placeholder="Search in..."
                required
              />
              <button name="search" hidden type="submit">Search</button>
            </div>
            <!-- End .header-search-wrapper -->
          </form>
        </div>
        <!-- End .header-search -->

        {% include 'main/includes/cart.html' %}
        <!-- End .cart-dropdown -->
      </div>
      <!-- End .header-right -->
    </div>
    <!-- End .container -->
  </div>
  <!-- End .header-middle -->
</header>